"""empty message

Revision ID: c6d09435c1a1
Revises: aae4f0a31350
Create Date: 2022-11-19 14:01:06.340435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d09435c1a1'
down_revision = 'aae4f0a31350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'character_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('favorites', 'planet_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorites', 'planet_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('favorites', 'character_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
